package com.chinadci.springboot.gismapper;

 ;
 import com.chinadci.springboot.gisentity.Xzqh;
 import com.chinadci.springboot.gisentity.XzqhExample;
 import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XzqhMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xzqh
     *
     * @mbg.generated
     */
    long countByExample(XzqhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xzqh
     *
     * @mbg.generated
     */
    int deleteByExample(XzqhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xzqh
     *
     * @mbg.generated
     */
    int insert(Xzqh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xzqh
     *
     * @mbg.generated
     */
    int insertSelective(Xzqh record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xzqh
     *
     * @mbg.generated
     */
    List<Xzqh> selectByExample(XzqhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xzqh
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Xzqh record, @Param("example") XzqhExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xzqh
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Xzqh record, @Param("example") XzqhExample example);
}