package com.chinadci.springboot.entity;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;
import java.util.Date;

public class Affixinfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.affixid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "附件ID",name = "affixid")
    private String affixid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.affixename
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "附件英文名称",name = "affixename")
    private String affixename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.affixcname
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "附件中文名称",name = "affixcname")
    private String affixcname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.extname
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "附件后缀  如  word,txt，jpg",name = "extname")
    private String extname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.filemgid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "附件mgdbid",name = "filemgid")
    private String filemgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.filesize
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "附件大小",name = "filesize")
    private Double filesize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.createtime
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "创建时间",name = "createtime")
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.createuser
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "创建人",name = "createuser")
    private String createuser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.previewurl
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "附件url",name = "previewurl")
    private String previewurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.mainid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "附件id",name = "mainid")
    private String mainid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.type
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "0本地上传1项目裁量库2常用材料",name = "type")
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.directoryid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "目录id",name = "directoryid")
    private String directoryid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column affixinfo.opcount
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    @ApiModelProperty(value = "定时器同步pdf文件错误记录",name = "opcount")
    private Integer opcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table affixinfo
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.affixid
     *
     * @return the value of affixinfo.affixid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public String getAffixid() {
        return affixid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.affixid
     *
     * @param affixid the value for affixinfo.affixid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setAffixid(String affixid) {
        this.affixid = affixid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.affixename
     *
     * @return the value of affixinfo.affixename
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public String getAffixename() {
        return affixename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.affixename
     *
     * @param affixename the value for affixinfo.affixename
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setAffixename(String affixename) {
        this.affixename = affixename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.affixcname
     *
     * @return the value of affixinfo.affixcname
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public String getAffixcname() {
        return affixcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.affixcname
     *
     * @param affixcname the value for affixinfo.affixcname
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setAffixcname(String affixcname) {
        this.affixcname = affixcname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.extname
     *
     * @return the value of affixinfo.extname
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public String getExtname() {
        return extname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.extname
     *
     * @param extname the value for affixinfo.extname
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setExtname(String extname) {
        this.extname = extname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.filemgid
     *
     * @return the value of affixinfo.filemgid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public String getFilemgid() {
        return filemgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.filemgid
     *
     * @param filemgid the value for affixinfo.filemgid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setFilemgid(String filemgid) {
        this.filemgid = filemgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.filesize
     *
     * @return the value of affixinfo.filesize
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public Double getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.filesize
     *
     * @param filesize the value for affixinfo.filesize
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setFilesize(Double filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.createtime
     *
     * @return the value of affixinfo.createtime
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.createtime
     *
     * @param createtime the value for affixinfo.createtime
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.createuser
     *
     * @return the value of affixinfo.createuser
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public String getCreateuser() {
        return createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.createuser
     *
     * @param createuser the value for affixinfo.createuser
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setCreateuser(String createuser) {
        this.createuser = createuser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.previewurl
     *
     * @return the value of affixinfo.previewurl
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public String getPreviewurl() {
        return previewurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.previewurl
     *
     * @param previewurl the value for affixinfo.previewurl
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setPreviewurl(String previewurl) {
        this.previewurl = previewurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.mainid
     *
     * @return the value of affixinfo.mainid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public String getMainid() {
        return mainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.mainid
     *
     * @param mainid the value for affixinfo.mainid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setMainid(String mainid) {
        this.mainid = mainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.type
     *
     * @return the value of affixinfo.type
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.type
     *
     * @param type the value for affixinfo.type
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.directoryid
     *
     * @return the value of affixinfo.directoryid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public String getDirectoryid() {
        return directoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.directoryid
     *
     * @param directoryid the value for affixinfo.directoryid
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setDirectoryid(String directoryid) {
        this.directoryid = directoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column affixinfo.opcount
     *
     * @return the value of affixinfo.opcount
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public Integer getOpcount() {
        return opcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column affixinfo.opcount
     *
     * @param opcount the value for affixinfo.opcount
     *
     * @mbg.generated Tue Nov 09 15:25:12 CST 2021
     */
    public void setOpcount(Integer opcount) {
        this.opcount = opcount;
    }
}