package com.chinadci.springboot.gisentity;

import io.swagger.annotations.ApiModelProperty;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table xzqh
 */
public class Xzqh implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.objectid
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "objectid")
    private Integer objectid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.xian
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "xian")
    private String xian;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.xiang
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "xiang")
    private String xiang;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.xian_name
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "xian_name")
    private String xianName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.xiang_name
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "xiang_name")
    private String xiangName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.rank
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "rank")
    private String rank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.sindex
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "sindex")
    private String sindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.name
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "name")
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.pcode
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "pcode")
    private String pcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.code
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "code")
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.year
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "year")
    private String year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.shape
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "shape")
    private Object shape;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xzqh.nf_code
     *
     * @mbg.generated
     */
    @ApiModelProperty(value = "null",name = "nf_code")
    private String nfCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table xzqh
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.objectid
     *
     * @return the value of xzqh.objectid
     *
     * @mbg.generated
     */
    public Integer getObjectid() {
        return objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.objectid
     *
     * @param objectid the value for xzqh.objectid
     *
     * @mbg.generated
     */
    public void setObjectid(Integer objectid) {
        this.objectid = objectid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.xian
     *
     * @return the value of xzqh.xian
     *
     * @mbg.generated
     */
    public String getXian() {
        return xian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.xian
     *
     * @param xian the value for xzqh.xian
     *
     * @mbg.generated
     */
    public void setXian(String xian) {
        this.xian = xian;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.xiang
     *
     * @return the value of xzqh.xiang
     *
     * @mbg.generated
     */
    public String getXiang() {
        return xiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.xiang
     *
     * @param xiang the value for xzqh.xiang
     *
     * @mbg.generated
     */
    public void setXiang(String xiang) {
        this.xiang = xiang;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.xian_name
     *
     * @return the value of xzqh.xian_name
     *
     * @mbg.generated
     */
    public String getXianName() {
        return xianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.xian_name
     *
     * @param xianName the value for xzqh.xian_name
     *
     * @mbg.generated
     */
    public void setXianName(String xianName) {
        this.xianName = xianName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.xiang_name
     *
     * @return the value of xzqh.xiang_name
     *
     * @mbg.generated
     */
    public String getXiangName() {
        return xiangName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.xiang_name
     *
     * @param xiangName the value for xzqh.xiang_name
     *
     * @mbg.generated
     */
    public void setXiangName(String xiangName) {
        this.xiangName = xiangName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.rank
     *
     * @return the value of xzqh.rank
     *
     * @mbg.generated
     */
    public String getRank() {
        return rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.rank
     *
     * @param rank the value for xzqh.rank
     *
     * @mbg.generated
     */
    public void setRank(String rank) {
        this.rank = rank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.sindex
     *
     * @return the value of xzqh.sindex
     *
     * @mbg.generated
     */
    public String getSindex() {
        return sindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.sindex
     *
     * @param sindex the value for xzqh.sindex
     *
     * @mbg.generated
     */
    public void setSindex(String sindex) {
        this.sindex = sindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.name
     *
     * @return the value of xzqh.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.name
     *
     * @param name the value for xzqh.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.pcode
     *
     * @return the value of xzqh.pcode
     *
     * @mbg.generated
     */
    public String getPcode() {
        return pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.pcode
     *
     * @param pcode the value for xzqh.pcode
     *
     * @mbg.generated
     */
    public void setPcode(String pcode) {
        this.pcode = pcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.code
     *
     * @return the value of xzqh.code
     *
     * @mbg.generated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.code
     *
     * @param code the value for xzqh.code
     *
     * @mbg.generated
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.year
     *
     * @return the value of xzqh.year
     *
     * @mbg.generated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.year
     *
     * @param year the value for xzqh.year
     *
     * @mbg.generated
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.shape
     *
     * @return the value of xzqh.shape
     *
     * @mbg.generated
     */
    public Object getShape() {
        return shape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.shape
     *
     * @param shape the value for xzqh.shape
     *
     * @mbg.generated
     */
    public void setShape(Object shape) {
        this.shape = shape;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xzqh.nf_code
     *
     * @return the value of xzqh.nf_code
     *
     * @mbg.generated
     */
    public String getNfCode() {
        return nfCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xzqh.nf_code
     *
     * @param nfCode the value for xzqh.nf_code
     *
     * @mbg.generated
     */
    public void setNfCode(String nfCode) {
        this.nfCode = nfCode;
    }
}
 